// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhkM5RNdjv0oWAi1nEJ177rQctR-8_Q4M',
    appId: '1:979014902079:web:6d7eecbc320362d146338a',
    messagingSenderId: '979014902079',
    projectId: 'eyexaminer-refactor',
    authDomain: 'eyexaminer-refactor.firebaseapp.com',
    storageBucket: 'eyexaminer-refactor.firebasestorage.app',
    measurementId: 'G-0ZCTEHJ3DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1qjpP2cctvoZ6Aiv02CzfxO563IkJ7Y',
    appId: '1:979014902079:android:8ec33ce1f536388246338a',
    messagingSenderId: '979014902079',
    projectId: 'eyexaminer-refactor',
    storageBucket: 'eyexaminer-refactor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTki8Cr7fVoQ4nbEXXbTIHp-xhOMU1CGU',
    appId: '1:979014902079:ios:6c4b5bc04edadb8e46338a',
    messagingSenderId: '979014902079',
    projectId: 'eyexaminer-refactor',
    storageBucket: 'eyexaminer-refactor.firebasestorage.app',
    iosBundleId: 'com.example.eyexaminerRefactor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTki8Cr7fVoQ4nbEXXbTIHp-xhOMU1CGU',
    appId: '1:979014902079:ios:6c4b5bc04edadb8e46338a',
    messagingSenderId: '979014902079',
    projectId: 'eyexaminer-refactor',
    storageBucket: 'eyexaminer-refactor.firebasestorage.app',
    iosBundleId: 'com.example.eyexaminerRefactor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhkM5RNdjv0oWAi1nEJ177rQctR-8_Q4M',
    appId: '1:979014902079:web:b2e26f9f484abc5446338a',
    messagingSenderId: '979014902079',
    projectId: 'eyexaminer-refactor',
    authDomain: 'eyexaminer-refactor.firebaseapp.com',
    storageBucket: 'eyexaminer-refactor.firebasestorage.app',
    measurementId: 'G-K46FN6S4M3',
  );

}